chore(deps): update all dependencies (#33)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@playwright/test](https://playwright.dev)
([source](https://togithub.com/microsoft/playwright)) | [`1.38.1` ->
`1.39.0`](https://renovatebot.com/diffs/npm/@playwright%2ftest/1.38.1/1.39.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@playwright%2ftest/1.39.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@playwright%2ftest/1.39.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@playwright%2ftest/1.38.1/1.39.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@playwright%2ftest/1.38.1/1.39.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) |
[`20.8.3` ->
`20.8.6`](https://renovatebot.com/diffs/npm/@types%2fnode/20.8.3/20.8.6)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/20.8.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/20.8.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/20.8.3/20.8.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/20.8.3/20.8.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [happy-dom](https://togithub.com/capricorn86/happy-dom) | [`12.9.0` ->
`12.9.1`](https://renovatebot.com/diffs/npm/happy-dom/12.9.0/12.9.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/happy-dom/12.9.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/happy-dom/12.9.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/happy-dom/12.9.0/12.9.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/happy-dom/12.9.0/12.9.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [vue-tsc](https://togithub.com/vuejs/language-tools) | [`1.8.16` ->
`1.8.19`](https://renovatebot.com/diffs/npm/vue-tsc/1.8.16/1.8.19) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/vue-tsc/1.8.19?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/vue-tsc/1.8.19?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/vue-tsc/1.8.16/1.8.19?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/vue-tsc/1.8.16/1.8.19?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>microsoft/playwright (@&#8203;playwright/test)</summary>

###
[`v1.39.0`](https://togithub.com/microsoft/playwright/releases/tag/v1.39.0)

[Compare
Source](https://togithub.com/microsoft/playwright/compare/v1.38.1...v1.39.0)

#### Add custom matchers to your expect

You can extend Playwright assertions by providing custom matchers. These
matchers will be available on the expect object.

```js
import { expect as baseExpect } from '@&#8203;playwright/test';
export const expect = baseExpect.extend({
  async toHaveAmount(locator: Locator, expected: number, options?: { timeout?: number }) {
    // ... see documentation for how to write matchers.
  },
});

test('pass', async ({ page }) => {
  await expect(page.getByTestId('cart')).toHaveAmount(5);
});
```

See the documentation [for a full
example](https://playwright.dev/docs/test-configuration#add-custom-matchers-using-expectextend).

#### Merge test fixtures

You can now merge test fixtures from multiple files or modules:

```js
import { mergeTests } from '@&#8203;playwright/test';
import { test as dbTest } from 'database-test-utils';
import { test as a11yTest } from 'a11y-test-utils';

export const test = mergeTests(dbTest, a11yTest);
```

```js
import { test } from './fixtures';

test('passes', async ({ database, page, a11y }) => {
  // use database and a11y fixtures.
});
```

#### Merge custom expect matchers

You can now merge custom expect matchers from multiple files or modules:

```js
import { mergeTests, mergeExpects } from '@&#8203;playwright/test';
import { test as dbTest, expect as dbExpect } from 'database-test-utils';
import { test as a11yTest, expect as a11yExpect } from 'a11y-test-utils';

export const test = mergeTests(dbTest, a11yTest);
export const expect = mergeExpects(dbExpect, a11yExpect);
```

```js
import { test, expect } from './fixtures';

test('passes', async ({ page, database }) => {
  await expect(database).toHaveDatabaseUser('admin');
  await expect(page).toPassA11yAudit();
});
```

#### Hide implementation details: box test steps

You can mark a
[`test.step()`](https://playwright.dev/docs/api/class-test#test-step) as
"boxed" so that errors inside it point to the step call site.

```js
async function login(page) {
  await test.step('login', async () => {
    // ...
  }, { box: true });  // Note the "box" option here.
}
```

```txt
Error: Timed out 5000ms waiting for expect(locator).toBeVisible()
  ... error details omitted ...

  14 |   await page.goto('https://github.com/login');
> 15 |   await login(page);
     |         ^
  16 | });
```

See
[`test.step()`](https://playwright.dev/docs/api/class-test#test-step)
documentation for a full example.

#### New APIs

-
[`expect(locator).toHaveAttribute(name)`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-attribute-2)

#### Browser Versions

-   Chromium 119.0.6045.9
-   Mozilla Firefox 118.0.1
-   WebKit 17.4

This version was also tested against the following stable channels:

-   Google Chrome 118
-   Microsoft Edge 118

</details>

<details>
<summary>capricorn86/happy-dom (happy-dom)</summary>

###
[`v12.9.1`](https://togithub.com/capricorn86/happy-dom/releases/tag/v12.9.1)

[Compare
Source](https://togithub.com/capricorn86/happy-dom/compare/v12.9.0...v12.9.1)

##### :construction_worker_man: Patch fixes

- Fixes typo in documentation.
([#&#8203;1123](https://togithub.com/capricorn86/happy-dom/issues/1123))

***

Thank you [@&#8203;goring](https://togithub.com/goring) for your
contribution!

</details>

<details>
<summary>vuejs/language-tools (vue-tsc)</summary>

###
[`v1.8.19`](https://togithub.com/vuejs/language-tools/blob/HEAD/CHANGELOG.md#1819-20231011)

[Compare
Source](https://togithub.com/vuejs/language-tools/compare/46ef0d608f43569a8e370d1105bfcf334fcaec13...2e17f3c9cfa827c71e1ed07331730b3ee2596b76)

- feat: no longer checking save time
([#&#8203;3650](https://togithub.com/vuejs/language-tools/issues/3650))
- fix(ts-plugin): tsserver doesnt have updated list of external files
when new vue files are added (required TS 5.3)
([#&#8203;3555](https://togithub.com/vuejs/language-tools/issues/3555))
([#&#8203;3649](https://togithub.com/vuejs/language-tools/issues/3649))
- fix: false positive error when accessing local variables in
defineProps parameter
([#&#8203;3643](https://togithub.com/vuejs/language-tools/issues/3643))
([#&#8203;3644](https://togithub.com/vuejs/language-tools/issues/3644))
- thanks [@&#8203;so1ve](https://togithub.com/so1ve)

##### Full-time Support by

<table>
<tbody>
  <tr>
    <td>
<a href="https://stackblitz.com/"><img
src="https://raw.githubusercontent.com/vuejs/language-tools/HEAD/.github/sponsors/StackBlitz.png"
height="80" /></a>
	</td>
<td><h4><a
href="https://blog.stackblitz.com/posts/webcontainer-api-is-here/">WebContainer
API is here.</a></h4></td>
  </tr>
</tbody>
</table>

##### Our Platinum Sponsors

<table>
<tbody>
  <tr>
    <td>
<a href="https://nuxt.com/"><img
src="https://raw.githubusercontent.com/vuejs/language-tools/HEAD/.github/sponsors/nuxt.svg"
height="60" /></a>
	</td>
    <td>The Intuitive Web Framework</td>
  </tr>
  <tr>
    <td>
<a href="https://vuejs.org/"><img
src="https://raw.githubusercontent.com/vuejs/language-tools/HEAD/.github/sponsors/vue.png"
height="80" /></a>
	</td>
    <td>The Progressive JavaScript Framework</td>
  </tr>
</tbody>
</table>

##### Our Silver Sponsors

<table>
<tbody>
  <tr>
    <td>
		<p align="center">
<a href="https://www.prefect.io/"><img
src="https://raw.githubusercontent.com/vuejs/language-tools/HEAD/.github/sponsors/prefect.svg"
height="40" /></a>
</p>
	</td>
  </tr>
</tbody>
</table>

<h5>
	Add you via
<a href="https://togithub.com/sponsors/johnsoncodehk">GitHub
Sponsors</a>
	or
	<a href="https://opencollective.com/volarjs">Open Collective</a>
</h5>

###
[`v1.8.18`](https://togithub.com/vuejs/language-tools/blob/HEAD/CHANGELOG.md#1818-2023109)

[Compare
Source](https://togithub.com/vuejs/language-tools/compare/v1.8.17...46ef0d608f43569a8e370d1105bfcf334fcaec13)

##### Upgrade required VSCode version to 1.82.0
([#&#8203;3642](https://togithub.com/vuejs/language-tools/issues/3642))

###
[`v1.8.17`](https://togithub.com/vuejs/language-tools/blob/HEAD/CHANGELOG.md#1817-2023109)

[Compare
Source](https://togithub.com/vuejs/language-tools/compare/f9e281db3f47f9a3f94c79dbbf81102cba01eb5d...v1.8.17)

- fix: extension cannot run on vscode versions lower than 1.82.0
([#&#8203;3631](https://togithub.com/vuejs/language-tools/issues/3631))
([#&#8203;3635](https://togithub.com/vuejs/language-tools/issues/3635))
- fix: make `defineProps` work when reading a property from
`defineProps()`
([#&#8203;3633](https://togithub.com/vuejs/language-tools/issues/3633))
- thanks [@&#8203;so1ve](https://togithub.com/so1ve)
- fix: avoid reading `props` from `__VLS_ctx`
([#&#8203;3636](https://togithub.com/vuejs/language-tools/issues/3636))
- thanks [@&#8203;so1ve](https://togithub.com/so1ve)
- fix: regression with `defineExpose`
([#&#8203;3639](https://togithub.com/vuejs/language-tools/issues/3639))
- thanks [@&#8203;so1ve](https://togithub.com/so1ve)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on Monday" in timezone
Europe/Helsinki, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/slipmatio/logger).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4xOS4yIiwidXBkYXRlZEluVmVyIjoiMzcuMTkuMiIsInRhcmdldEJyYW5jaCI6Im1haW4ifQ==-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>